# Generated by Django 2.1.7 on 2019-02-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_course_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='mandatory',
            field=models.ManyToManyField(blank=True, to='logic.Course'),
        ),
    ]
